// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmhdjuzmrrnpsdyswfbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtaGRqdXptcnJucHNkeXN3ZmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MDYxODAsImV4cCI6MjA3ODI4MjE4MH0.Wa6T1Gj9EzMZ2iJwd7V7FtJKAFaOgLwGcba3tYuAD-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});