// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgofqsxdgpooqxpqitlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nb2Zxc3hkZ3Bvb3F4cHFpdGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDk5NzIsImV4cCI6MjA3NzgyNTk3Mn0.rtqOP7TFZBZ8q-cem98VOCayi5ngGoPsG_21ee6py-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});